name: gitops-validate

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "gitops/**"
  push:
    branches: [ "main" ]
    paths:
      - "gitops/**"
  workflow_dispatch:

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          set -euo pipefail
          curl -sSL -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/
          kubeconform -v

      - name: Validate Kubernetes manifests under gitops/**
        shell: bash
        run: |
          set -euo pipefail
          # Collect YAML manifests, excluding common Helm values filenames
          mapfile -d '' FILES < <(find gitops -type f \( -name '*.yaml' -o -name '*.yml' \) \
                                   ! -name 'values.yaml' ! -name '*-values.yaml' -print0)
          if [[ ${#FILES[@]} -eq 0 ]]; then
            echo "No Kubernetes manifests found under gitops/. Skipping."
            exit 0
          fi
          echo "Validating ${#FILES[@]} manifest files..."
          kubeconform -strict -ignore-missing-schemas -summary "${FILES[@]}"

