apiVersion: v1
kind: Service
metadata:
  name: gin-api
  namespace: tickboard
  labels:
    app: gin-api
spec:
  type: ClusterIP
  selector:
    app: gin-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082

