apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Namespaced application workloads managed via GitOps
  sourceRepos:
    - https://github.com/TickBoard/Deploy.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  # Allow Namespace to be managed by apps (needed because base includes namespace.yaml)
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  orphanedResources:
    warn: true
