apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tickboard
resources:
  - ../../base
  - serviceaccount-patch.yaml
images:
  - name: ghcr.io/OWNER/tickboard-gin-api
    newName: harbor.czhuang.dev/tickboard/gin-api
        newTag: latest
  - name: ghcr.io/OWNER/tickboard-frontend
    newName: harbor.czhuang.dev/tickboard/frontend
        newTag: latest
